#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HakemFiksturOtomasyon
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HakemOtomasyon")]
	public partial class HakemOtomasyonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFikstur(Fikstur instance);
    partial void UpdateFikstur(Fikstur instance);
    partial void DeleteFikstur(Fikstur instance);
    partial void InsertHakem(Hakem instance);
    partial void UpdateHakem(Hakem instance);
    partial void DeleteHakem(Hakem instance);
    partial void InsertLig(Lig instance);
    partial void UpdateLig(Lig instance);
    partial void DeleteLig(Lig instance);
    partial void InsertSehir(Sehir instance);
    partial void UpdateSehir(Sehir instance);
    partial void DeleteSehir(Sehir instance);
    partial void InsertStadyum(Stadyum instance);
    partial void UpdateStadyum(Stadyum instance);
    partial void DeleteStadyum(Stadyum instance);
    partial void InsertTakim(Takim instance);
    partial void UpdateTakim(Takim instance);
    partial void DeleteTakim(Takim instance);
    #endregion
		
		public HakemOtomasyonDataContext() : 
				base(global::HakemFiksturOtomasyon.Properties.Settings.Default.HakemOtomasyonConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public HakemOtomasyonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HakemOtomasyonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HakemOtomasyonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HakemOtomasyonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Fikstur> Fiksturs
		{
			get
			{
				return this.GetTable<Fikstur>();
			}
		}
		
		public System.Data.Linq.Table<Hakem> Hakems
		{
			get
			{
				return this.GetTable<Hakem>();
			}
		}
		
		public System.Data.Linq.Table<Lig> Ligs
		{
			get
			{
				return this.GetTable<Lig>();
			}
		}
		
		public System.Data.Linq.Table<Sehir> Sehirs
		{
			get
			{
				return this.GetTable<Sehir>();
			}
		}
		
		public System.Data.Linq.Table<Stadyum> Stadyums
		{
			get
			{
				return this.GetTable<Stadyum>();
			}
		}
		
		public System.Data.Linq.Table<Takim> Takims
		{
			get
			{
				return this.GetTable<Takim>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fikstur")]
	public partial class Fikstur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ilkTakim;
		
		private string _ikinciTakim;
		
		private string _tarih;
		
		private string _saat;
		
		private string _hafta;
		
		private string _lig;
		
		private string _ortaHakem;
		
		private string _yardimciHakem;
		
		private string _dorduncuHakem;
		
		private string _stadyum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnilkTakimChanging(string value);
    partial void OnilkTakimChanged();
    partial void OnikinciTakimChanging(string value);
    partial void OnikinciTakimChanged();
    partial void OntarihChanging(string value);
    partial void OntarihChanged();
    partial void OnsaatChanging(string value);
    partial void OnsaatChanged();
    partial void OnhaftaChanging(string value);
    partial void OnhaftaChanged();
    partial void OnligChanging(string value);
    partial void OnligChanged();
    partial void OnortaHakemChanging(string value);
    partial void OnortaHakemChanged();
    partial void OnyardimciHakemChanging(string value);
    partial void OnyardimciHakemChanged();
    partial void OndorduncuHakemChanging(string value);
    partial void OndorduncuHakemChanged();
    partial void OnstadyumChanging(string value);
    partial void OnstadyumChanged();
    #endregion
		
		public Fikstur()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilkTakim", DbType="NVarChar(50)")]
		public string ilkTakim
		{
			get
			{
				return this._ilkTakim;
			}
			set
			{
				if ((this._ilkTakim != value))
				{
					this.OnilkTakimChanging(value);
					this.SendPropertyChanging();
					this._ilkTakim = value;
					this.SendPropertyChanged("ilkTakim");
					this.OnilkTakimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ikinciTakim", DbType="NVarChar(50)")]
		public string ikinciTakim
		{
			get
			{
				return this._ikinciTakim;
			}
			set
			{
				if ((this._ikinciTakim != value))
				{
					this.OnikinciTakimChanging(value);
					this.SendPropertyChanging();
					this._ikinciTakim = value;
					this.SendPropertyChanged("ikinciTakim");
					this.OnikinciTakimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="Char(10)")]
		public string tarih
		{
			get
			{
				return this._tarih;
			}
			set
			{
				if ((this._tarih != value))
				{
					this.OntarihChanging(value);
					this.SendPropertyChanging();
					this._tarih = value;
					this.SendPropertyChanged("tarih");
					this.OntarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saat", DbType="Char(5)")]
		public string saat
		{
			get
			{
				return this._saat;
			}
			set
			{
				if ((this._saat != value))
				{
					this.OnsaatChanging(value);
					this.SendPropertyChanging();
					this._saat = value;
					this.SendPropertyChanged("saat");
					this.OnsaatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hafta", DbType="NVarChar(20)")]
		public string hafta
		{
			get
			{
				return this._hafta;
			}
			set
			{
				if ((this._hafta != value))
				{
					this.OnhaftaChanging(value);
					this.SendPropertyChanging();
					this._hafta = value;
					this.SendPropertyChanged("hafta");
					this.OnhaftaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lig", DbType="NVarChar(40)")]
		public string lig
		{
			get
			{
				return this._lig;
			}
			set
			{
				if ((this._lig != value))
				{
					this.OnligChanging(value);
					this.SendPropertyChanging();
					this._lig = value;
					this.SendPropertyChanged("lig");
					this.OnligChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ortaHakem", DbType="NVarChar(50)")]
		public string ortaHakem
		{
			get
			{
				return this._ortaHakem;
			}
			set
			{
				if ((this._ortaHakem != value))
				{
					this.OnortaHakemChanging(value);
					this.SendPropertyChanging();
					this._ortaHakem = value;
					this.SendPropertyChanged("ortaHakem");
					this.OnortaHakemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yardimciHakem", DbType="NVarChar(50)")]
		public string yardimciHakem
		{
			get
			{
				return this._yardimciHakem;
			}
			set
			{
				if ((this._yardimciHakem != value))
				{
					this.OnyardimciHakemChanging(value);
					this.SendPropertyChanging();
					this._yardimciHakem = value;
					this.SendPropertyChanged("yardimciHakem");
					this.OnyardimciHakemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dorduncuHakem", DbType="NVarChar(50)")]
		public string dorduncuHakem
		{
			get
			{
				return this._dorduncuHakem;
			}
			set
			{
				if ((this._dorduncuHakem != value))
				{
					this.OndorduncuHakemChanging(value);
					this.SendPropertyChanging();
					this._dorduncuHakem = value;
					this.SendPropertyChanged("dorduncuHakem");
					this.OndorduncuHakemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stadyum", DbType="NVarChar(50)")]
		public string stadyum
		{
			get
			{
				return this._stadyum;
			}
			set
			{
				if ((this._stadyum != value))
				{
					this.OnstadyumChanging(value);
					this.SendPropertyChanging();
					this._stadyum = value;
					this.SendPropertyChanged("stadyum");
					this.OnstadyumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hakem")]
	public partial class Hakem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _adi;
		
		private string _soyadi;
		
		private string _turu;
		
		private string _klasmani;
		
		private string _bolgesi;
		
		private System.Nullable<int> _referansHakem;
		
		private EntitySet<Hakem> _Hakems;
		
		private EntityRef<Hakem> _Hakem1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    partial void OnsoyadiChanging(string value);
    partial void OnsoyadiChanged();
    partial void OnturuChanging(string value);
    partial void OnturuChanged();
    partial void OnklasmaniChanging(string value);
    partial void OnklasmaniChanged();
    partial void OnbolgesiChanging(string value);
    partial void OnbolgesiChanged();
    partial void OnreferansHakemChanging(System.Nullable<int> value);
    partial void OnreferansHakemChanged();
    #endregion
		
		public Hakem()
		{
			this._Hakems = new EntitySet<Hakem>(new Action<Hakem>(this.attach_Hakems), new Action<Hakem>(this.detach_Hakems));
			this._Hakem1 = default(EntityRef<Hakem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="VarChar(50)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyadi", DbType="VarChar(50)")]
		public string soyadi
		{
			get
			{
				return this._soyadi;
			}
			set
			{
				if ((this._soyadi != value))
				{
					this.OnsoyadiChanging(value);
					this.SendPropertyChanging();
					this._soyadi = value;
					this.SendPropertyChanged("soyadi");
					this.OnsoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turu", DbType="VarChar(50)")]
		public string turu
		{
			get
			{
				return this._turu;
			}
			set
			{
				if ((this._turu != value))
				{
					this.OnturuChanging(value);
					this.SendPropertyChanging();
					this._turu = value;
					this.SendPropertyChanged("turu");
					this.OnturuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_klasmani", DbType="VarChar(50)")]
		public string klasmani
		{
			get
			{
				return this._klasmani;
			}
			set
			{
				if ((this._klasmani != value))
				{
					this.OnklasmaniChanging(value);
					this.SendPropertyChanging();
					this._klasmani = value;
					this.SendPropertyChanged("klasmani");
					this.OnklasmaniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bolgesi", DbType="VarChar(50)")]
		public string bolgesi
		{
			get
			{
				return this._bolgesi;
			}
			set
			{
				if ((this._bolgesi != value))
				{
					this.OnbolgesiChanging(value);
					this.SendPropertyChanging();
					this._bolgesi = value;
					this.SendPropertyChanged("bolgesi");
					this.OnbolgesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referansHakem", DbType="Int")]
		public System.Nullable<int> referansHakem
		{
			get
			{
				return this._referansHakem;
			}
			set
			{
				if ((this._referansHakem != value))
				{
					if (this._Hakem1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnreferansHakemChanging(value);
					this.SendPropertyChanging();
					this._referansHakem = value;
					this.SendPropertyChanged("referansHakem");
					this.OnreferansHakemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hakem_Hakem", Storage="_Hakems", ThisKey="id", OtherKey="referansHakem")]
		public EntitySet<Hakem> Hakems
		{
			get
			{
				return this._Hakems;
			}
			set
			{
				this._Hakems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hakem_Hakem", Storage="_Hakem1", ThisKey="referansHakem", OtherKey="id", IsForeignKey=true)]
		public Hakem Hakem1
		{
			get
			{
				return this._Hakem1.Entity;
			}
			set
			{
				Hakem previousValue = this._Hakem1.Entity;
				if (((previousValue != value) 
							|| (this._Hakem1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hakem1.Entity = null;
						previousValue.Hakems.Remove(this);
					}
					this._Hakem1.Entity = value;
					if ((value != null))
					{
						value.Hakems.Add(this);
						this._referansHakem = value.id;
					}
					else
					{
						this._referansHakem = default(Nullable<int>);
					}
					this.SendPropertyChanged("Hakem1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hakems(Hakem entity)
		{
			this.SendPropertyChanging();
			entity.Hakem1 = this;
		}
		
		private void detach_Hakems(Hakem entity)
		{
			this.SendPropertyChanging();
			entity.Hakem1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lig")]
	public partial class Lig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _adi;
		
		private EntitySet<Takim> _Takims;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    #endregion
		
		public Lig()
		{
			this._Takims = new EntitySet<Takim>(new Action<Takim>(this.attach_Takims), new Action<Takim>(this.detach_Takims));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="VarChar(50)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lig_Takim", Storage="_Takims", ThisKey="id", OtherKey="ligId")]
		public EntitySet<Takim> Takims
		{
			get
			{
				return this._Takims;
			}
			set
			{
				this._Takims.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Takims(Takim entity)
		{
			this.SendPropertyChanging();
			entity.Lig = this;
		}
		
		private void detach_Takims(Takim entity)
		{
			this.SendPropertyChanging();
			entity.Lig = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sehir")]
	public partial class Sehir : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _adi;
		
		private EntitySet<Stadyum> _Stadyums;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    #endregion
		
		public Sehir()
		{
			this._Stadyums = new EntitySet<Stadyum>(new Action<Stadyum>(this.attach_Stadyums), new Action<Stadyum>(this.detach_Stadyums));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="VarChar(50)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sehir_Stadyum", Storage="_Stadyums", ThisKey="id", OtherKey="sehirId")]
		public EntitySet<Stadyum> Stadyums
		{
			get
			{
				return this._Stadyums;
			}
			set
			{
				this._Stadyums.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Stadyums(Stadyum entity)
		{
			this.SendPropertyChanging();
			entity.Sehir = this;
		}
		
		private void detach_Stadyums(Stadyum entity)
		{
			this.SendPropertyChanging();
			entity.Sehir = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stadyum")]
	public partial class Stadyum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _adi;
		
		private System.Nullable<int> _sehirId;
		
		private string _diger;
		
		private EntityRef<Sehir> _Sehir;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    partial void OnsehirIdChanging(System.Nullable<int> value);
    partial void OnsehirIdChanged();
    partial void OndigerChanging(string value);
    partial void OndigerChanged();
    #endregion
		
		public Stadyum()
		{
			this._Sehir = default(EntityRef<Sehir>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="VarChar(50)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sehirId", DbType="Int")]
		public System.Nullable<int> sehirId
		{
			get
			{
				return this._sehirId;
			}
			set
			{
				if ((this._sehirId != value))
				{
					if (this._Sehir.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsehirIdChanging(value);
					this.SendPropertyChanging();
					this._sehirId = value;
					this.SendPropertyChanged("sehirId");
					this.OnsehirIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diger", DbType="VarChar(50)")]
		public string diger
		{
			get
			{
				return this._diger;
			}
			set
			{
				if ((this._diger != value))
				{
					this.OndigerChanging(value);
					this.SendPropertyChanging();
					this._diger = value;
					this.SendPropertyChanged("diger");
					this.OndigerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sehir_Stadyum", Storage="_Sehir", ThisKey="sehirId", OtherKey="id", IsForeignKey=true)]
		public Sehir Sehir
		{
			get
			{
				return this._Sehir.Entity;
			}
			set
			{
				Sehir previousValue = this._Sehir.Entity;
				if (((previousValue != value) 
							|| (this._Sehir.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sehir.Entity = null;
						previousValue.Stadyums.Remove(this);
					}
					this._Sehir.Entity = value;
					if ((value != null))
					{
						value.Stadyums.Add(this);
						this._sehirId = value.id;
					}
					else
					{
						this._sehirId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Sehir");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Takim")]
	public partial class Takim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _adi;
		
		private System.Nullable<int> _ligId;
		
		private string _diger;
		
		private EntityRef<Lig> _Lig;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    partial void OnligIdChanging(System.Nullable<int> value);
    partial void OnligIdChanged();
    partial void OndigerChanging(string value);
    partial void OndigerChanged();
    #endregion
		
		public Takim()
		{
			this._Lig = default(EntityRef<Lig>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="VarChar(50)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ligId", DbType="Int")]
		public System.Nullable<int> ligId
		{
			get
			{
				return this._ligId;
			}
			set
			{
				if ((this._ligId != value))
				{
					if (this._Lig.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnligIdChanging(value);
					this.SendPropertyChanging();
					this._ligId = value;
					this.SendPropertyChanged("ligId");
					this.OnligIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diger", DbType="VarChar(50)")]
		public string diger
		{
			get
			{
				return this._diger;
			}
			set
			{
				if ((this._diger != value))
				{
					this.OndigerChanging(value);
					this.SendPropertyChanging();
					this._diger = value;
					this.SendPropertyChanged("diger");
					this.OndigerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lig_Takim", Storage="_Lig", ThisKey="ligId", OtherKey="id", IsForeignKey=true)]
		public Lig Lig
		{
			get
			{
				return this._Lig.Entity;
			}
			set
			{
				Lig previousValue = this._Lig.Entity;
				if (((previousValue != value) 
							|| (this._Lig.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lig.Entity = null;
						previousValue.Takims.Remove(this);
					}
					this._Lig.Entity = value;
					if ((value != null))
					{
						value.Takims.Add(this);
						this._ligId = value.id;
					}
					else
					{
						this._ligId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Lig");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
